# Generated by Django 6.0.3 on 2026-10-06 05:59

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalculationPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(choices=[('POLICY_A_LATEST_PASS', 'Policy A: Latest passing grade replaces failed attempt in SGPA & CGPA'), ('POLICY_B_FROZEN_SGPA', 'Policy B: Original SGPA frozen; CGPA updated with latest pass'), ('POLICY_C_HIGHEST_GRADE', 'Policy C: Highest grade achieved among all attempts'), ('POLICY_D_INSTITUTIONAL', 'Policy D: Custom institutional policy')], max_length=50, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('is_default', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='GradingSystem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(default='DEFAULT_EX_F', max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GradeRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('grade', models.CharField(db_index=True, max_length=10)),
                ('grade_point', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=4)),
                ('is_pass', models.BooleanField(default=True)),
                ('counts_for_sgpa', models.BooleanField(default=True)),
                ('counts_for_cgpa', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('grading_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='grading.gradingsystem')),
            ],
            options={
                'ordering': ['order', '-grade_point'],
                'unique_together': {('grading_system', 'grade')},
            },
        ),
    ]
