# Generated by Django 6.0.3 on 2026-10-06 05:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GradeSheet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_filename', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='gradesheets/%Y/%m/')),
                ('file_hash', models.CharField(db_index=True, max_length=64)),
                ('document_type', models.CharField(choices=[('GRADE_SHEET', 'Grade Sheet'), ('MARKS_MEMO', 'Marks Memo'), ('TRANSCRIPT', 'Transcript'), ('SUPPLEMENTARY_SHEET', 'Supplementary Grade Sheet'), ('BACKLOG_SHEET', 'Backlog Grade Sheet'), ('REVALUATION_RESULT', 'Revaluation Result'), ('UNKNOWN_DOCUMENT', 'Unknown Document')], default='GRADE_SHEET', max_length=40)),
                ('upload_status', models.CharField(choices=[('UPLOADED', 'Uploaded'), ('PROCESSING', 'Processing'), ('REVIEW_REQUIRED', 'Review Required'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], default='UPLOADED', max_length=30)),
                ('is_duplicate', models.BooleanField(default=False)),
                ('raw_header_text', models.TextField(blank=True)),
                ('detected_semester', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('semester_confidence', models.FloatField(default=0.0)),
                ('detected_exam_type', models.CharField(default='REGULAR', max_length=50)),
                ('exam_type_confidence', models.FloatField(default=0.0)),
                ('extracted_student_name', models.CharField(blank=True, max_length=255)),
                ('extracted_reg_no', models.CharField(blank=True, max_length=100)),
                ('extracted_institution', models.CharField(blank=True, max_length=255)),
                ('extracted_session', models.CharField(blank=True, max_length=100)),
                ('student_match_verified', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OCRExtraction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('raw_text', models.TextField(blank=True)),
                ('extracted_data', models.JSONField(default=dict)),
                ('overall_confidence', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OCRField',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('field_name', models.CharField(max_length=100)),
                ('raw_value', models.CharField(max_length=255)),
                ('normalized_value', models.CharField(max_length=255)),
                ('confidence', models.FloatField(default=1.0)),
                ('bounding_box', models.JSONField(default=list)),
                ('needs_review', models.BooleanField(default=False)),
                ('user_corrected', models.BooleanField(default=False)),
            ],
        ),
    ]
