# Generated by Django 6.0.3 on 2026-10-06 05:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gradesheets', '0001_initial'),
        ('semesters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradesheet',
            name='academic_attempt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gradesheets', to='semesters.academicattempt'),
        ),
    ]
