# Generated by Django 6.0.3 on 2026-10-06 05:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gradesheets', '0002_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradesheet',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gradesheets', to='students.studentprofile'),
        ),
        migrations.AddField(
            model_name='ocrextraction',
            name='gradesheet',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extraction', to='gradesheets.gradesheet'),
        ),
        migrations.AddField(
            model_name='ocrfield',
            name='extraction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='gradesheets.ocrextraction'),
        ),
    ]
