# Generated by Django 6.0.3 on 2026-10-06 05:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gradesheets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessingJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('PROCESSING', 'Processing'), ('REVIEW_REQUIRED', 'Review Required'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='QUEUED', max_length=30)),
                ('stage', models.CharField(default='INIT', max_length=100)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gradesheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processing_jobs', to='gradesheets.gradesheet')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
