# Generated by Django 6.0.3 on 2026-10-06 05:59

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gradesheets', '0002_initial'),
        ('semesters', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject_code', models.CharField(blank=True, max_length=50)),
                ('normalized_code', models.CharField(db_index=True, max_length=50)),
                ('subject_name', models.CharField(max_length=255)),
                ('default_credits', models.DecimalField(decimal_places=2, default=Decimal('3.00'), max_digits=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='students.studentprofile')),
            ],
            options={
                'ordering': ['normalized_code', 'subject_name'],
            },
        ),
        migrations.CreateModel(
            name='SubjectAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('raw_grade', models.CharField(max_length=10)),
                ('normalized_grade', models.CharField(db_index=True, max_length=10)),
                ('grade_point', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=4)),
                ('credits', models.DecimalField(decimal_places=2, default=Decimal('3.00'), max_digits=4)),
                ('is_pass', models.BooleanField(default=True)),
                ('confidence', models.FloatField(default=1.0)),
                ('user_corrected', models.BooleanField(default=False)),
                ('original_value', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('academic_attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_attempts', to='semesters.academicattempt')),
                ('source_gradesheet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subject_attempts', to='gradesheets.gradesheet')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='subjects.subject')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='EffectiveSubjectResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('effective_grade', models.CharField(max_length=10)),
                ('effective_grade_point', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=4)),
                ('effective_credits', models.DecimalField(decimal_places=2, default=Decimal('3.00'), max_digits=4)),
                ('is_pass', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='effective_results', to='semesters.semester')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='effective_results', to='subjects.subject')),
                ('selected_attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_for_effective', to='subjects.subjectattempt')),
            ],
            options={
                'ordering': ['subject__subject_name'],
                'unique_together': {('semester', 'subject')},
            },
        ),
    ]
