# Generated by Django 6.0.3 on 2026-10-06 05:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('attempt_number', models.PositiveSmallIntegerField(default=1)),
                ('exam_type', models.CharField(choices=[('REGULAR', 'Regular'), ('SUPPLEMENTARY', 'Supplementary'), ('BACKLOG', 'Backlog'), ('REVALUATION', 'Revaluation'), ('IMPROVEMENT', 'Improvement'), ('REPEAT', 'Repeat'), ('UNKNOWN', 'Unknown')], default='REGULAR', max_length=30)),
                ('raw_exam_type', models.CharField(blank=True, max_length=150)),
                ('academic_session', models.CharField(blank=True, max_length=100)),
                ('exam_date', models.CharField(blank=True, max_length=50)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['attempt_number'],
            },
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('semester_number', models.PositiveSmallIntegerField(db_index=True)),
                ('academic_year', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('BACKLOGS_PENDING', 'Backlogs Pending')], default='COMPLETED', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['semester_number'],
            },
        ),
    ]
