# Generated by Django 6.0.3 on 2026-10-06 05:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('semesters', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semesters', to='students.studentprofile'),
        ),
        migrations.AddField(
            model_name='academicattempt',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='semesters.semester'),
        ),
        migrations.AlterUniqueTogether(
            name='semester',
            unique_together={('student', 'semester_number')},
        ),
        migrations.AlterUniqueTogether(
            name='academicattempt',
            unique_together={('semester', 'attempt_number')},
        ),
    ]
