# Generated by Django 6.0.3 on 2026-10-06 05:59

import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicSummary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cgpa', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('total_credits_completed', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('total_backlogs_count', models.PositiveIntegerField(default=0)),
                ('cleared_backlogs_count', models.PositiveIntegerField(default=0)),
                ('active_backlogs_count', models.PositiveIntegerField(default=0)),
                ('highest_sgpa', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('lowest_sgpa', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SemesterResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sgpa', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('total_credits_registered', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('total_credits_earned', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('has_backlogs', models.BooleanField(default=False)),
                ('calculated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
