# Generated by Django 6.0.3 on 2026-10-06 05:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('calculations', '0001_initial'),
        ('semesters', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicsummary',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='academic_summary', to='students.studentprofile'),
        ),
        migrations.AddField(
            model_name='semesterresult',
            name='semester',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='semesters.semester'),
        ),
    ]
